# -- Configuração do Site --
# https://blowfish.page/docs/getting-started/

theme = "athaydelab"
baseURL = "https://athaydelab.com"
defaultContentLanguage = "pt-br"

enableRobotsTXT = true
enableGitInfo = true
summaryLength = 40

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 12

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  status = "status"
  series = "series"

[permalinks]
  artigos = "/:slug/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
      name = "tags"
      weight = 100

    [[related.indices]]
      name = "categories"
      weight = 100

    [[related.indices]]
      name = "series"
      weight = 50

    [[related.indices]]
      name = "status"
      weight = 20

    [[related.indices]]
      name = "date"
      weight = 10

    [[related.indices]]
      applyFilter = false
      name = "fragmentrefs"
      type = "fragments"
      weight = 10
