# -- Menu principal (header) --

[[main]]
  name = "~/artigos"
  url = "/"
  weight = 10

[[main]]
  name = "~/projetos"
  pageRef = "projetos"
  weight = 20

[[main]]
  name = "~/sobre"
  pageRef = "sobre"
  weight = 30

# -- Menu do rodape --

[[footer]]
  name = "YouTube"
  url = "https://www.youtube.com/@athaydelab"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/xathay"
  weight = 20

[[footer]]
  name = "Newsletter"
  pageRef = "newsletter"
  weight = 30

[[footer]]
  name = "Contato"
  pageRef = "contact"
  weight = 40
