# -- Parâmetros do Tema --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "athaydelab"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableA11y = true
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

replyByEmail = false

mainSections = ["posts"]

disableImageOptimization = false
disableTextInHeader = false

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/logo.png"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = ["telegram", "x-twitter", "email"]
  showZenMode = true
  showComments = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = true
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
